package com.game.playerassets.ia.strategy;

public enum TypeStrategy {
    ACTIVATE_AGGRESSIVE,
    ACTIVATE_MODERATE,
    ACTIVATE_RETREAT,
    INVOKE_AGGRESSIVE,
    INVOKE_MODERATE,
    INVOKE_RETREAT,
    CRYSTALLIZE_AGGRESSIVE,
    CRYSTALLIZE_MODERATE,
    CRYSTALLIZE_RETREAT,
    BONUS_AGGRESSIVE,
    BONUS_MODERATE,
    BONUS_RETREAT,
    DEFAULT,
    SIMPLE,
    COMBO,
    RANDOM
}
